# Site settings
# Cleaned for distribution

title: Example Blog
email: example@example.com
description: A clean and tech-styled blog theme.
baseurl: ""
url: ""
github_username: example

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap

future: true
